application: json-alerts
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
- url: .*
  script: main.py
